name: farmers
on: [push]
permissions:
  contents: write
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro 

          git fetch origin
          dvc metrics diff origin/main --md > report.md
          # Add figure to the report
          echo "## Validating results by region"
          echo '![](./by_region.png)' >> report.md
          cml comment create --publish report.md
          
